version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root
  
  desafio:
    build:
      context: .
    ports:
      - "8080:8080"  
    
